### ISSUE TITLE
Bright import fails

### ISSUE THREAD

**Issue by NiccyB** [hypercrypt/octopus-db#11]
Hi,

Running "php octo bright/import" generates the following:
```
nicholas@db10 ~/octopus-db$ php octo bright/import
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.glowmarkt.com/api/v0-1/resource/XXXXXXXXXXXXXXX/readings?period=PT30M&function=sum&from=2023-01-04T00%3A00%3A00&to=2023-01-04T10%3A47%3A00` resulted in a `404 Not Found` response in /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
<snip>
```

I used the passport ID from https://glowmarkt.com/#/pages/property-passport as the resource ID and the user/password I use to log into glowmarkt.com, which I assume is correct.

**Comment by hypercrypt** [comment]
Have you run `php octo list`. This will give you a list of uuids that are the ones to use. You'll likely be looking for something called `Smart Meter, electricity consumption` or `electricity consumption`. Does this match the UUID that you've added to the config?

**Comment by NiccyB** [comment]
Yes, but......
```
nicholas@db10 ~/octopus-db$ php octo list
list not found
nicholas@db10 ~/octopus-db$ php octo bright/list
PHP Fatal error:  Uncaught Error: Class "Console_Table" not found in /home/nicholas/octopus-db/scripts/bright/list.php:10
Stack trace:
#0 /home/nicholas/octopus-db/octo(31): require_once()
#1 {main}
  thrown in /home/nicholas/octopus-db/scripts/bright/list.php on line 10

Fatal error: Uncaught Error: Class "Console_Table" not found in /home/nicholas/octopus-db/scripts/bright/list.php:10
Stack trace:
#0 /home/nicholas/octopus-db/octo(31): require_once()
#1 {main}
  thrown in /home/nicholas/octopus-db/scripts/bright/list.php on line 10
```

**Comment by hypercrypt** [comment]
Ah, you'll need to run `composer install` after updating to 0.0.3 or 0.0.4. That'll fix it. Again, the second command is the one I mean. Sorry. Not having a great day today with all this 🤦🏻‍♂️

**Comment by NiccyB** [comment]
Ran `composer install` and saw a lot of "Deprecation Notice" messages, but no errors.

Re-ran `php octo bright/list` and saw two replies - "Smart Meter, electricity cost" and "Smart Meter, electricity consumption" with different values than I was using.

Changed the resource ID to the consumption value and ran `php octo bright/import` which didn't give any errors. A quick check of the database and....

It all appears to be working.

Yay!

Thank you again.

**Comment by hypercrypt** [comment]
Awesome!
