### ISSUE TITLE
[Bright] Tariff used for calculations shifted by half an hour

### ISSUE THREAD

**Issue by NiccyB** [hypercrypt/octopus-db#13]
I was looking through the figures trying to work out why the daily cost was coming out higher than expected when we use the figures from the Bright API, but this then gets corrected when the Octopus API figures are loaded in on top.

We're on Go with a cheap slot from 0030 to 0430. When Bright figures are loaded in, the cheap slot applied seems to be 0100-0500. When these figures are over-written by the Octopus data, the cheap slot moves back to 0030-0430.

![image](https://user-images.githubusercontent.com/31012803/211177311-81847694-6de0-4ab8-bada-2ddce45c6980.png)

**Comment by hypercrypt** [comment]
Are the readings correct (the consumption data)?

**Comment by NiccyB** [comment]
Yes, the readings are correct and in the correct time period. It's just that the price that is used is half an hour out.

**Comment by hypercrypt** [comment]
This is now fixed on `main`
