### ISSUE TITLE
Rename tables

### ISSUE THREAD

**Issue by NiccyB** [hypercrypt/octopus-db#14]
To keep the table naming consistent, should the tables price_h and usage_h be better named price_hh and usage_hh respectively?

**Comment by hypercrypt** [comment]
They actually have different meanings. The h in price_h is for human readable, like -h on a number of *nix command line tools (ls -lah or df -h .). It's there because the tables use Unix timestamp for times

**Comment by NiccyB** [comment]
Hi,
I suspected as much! No problem.

**Comment by hypercrypt** [comment]
Actually, thinking about - the correct solution is to rename the `billing_e_h` view to `billing_e_hour`
