### ISSUE TITLE
div by zero warning

### ISSUE THREAD

**Issue by NiccyB** [hypercrypt/octopus-db#5]
Hi,
I'm getting a
```
MariaDB [octopus]> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.000 sec)
```

warning when querying against `billing_e_day`. It turns out that one of the fixed tariffs which has loaded has created a record with zero kWh and null p/kWh figures.

![image](https://user-images.githubusercontent.com/31012803/210408783-a16d460a-0abf-4d6b-9503-d82048b4cb3b.png)

**Comment by hypercrypt** [comment]
This is fixed in 0.0.3
