### ISSUE TITLE
Add column "percent off-peak" to all views

### ISSUE THREAD

**Issue by NiccyB** [hypercrypt/octopus-db#6]
Hi,

`billing_e_month` defines the column `percent off-peak`, but this is not defined in any of the other views. It would be nice if it was. :-)

**Comment by hypercrypt** [comment]
I shall not be adding it to the half hour one as it'll always be 100% or 0% but all others will have this in the next release

**Comment by hypercrypt** [comment]
This is fixed in 0.0.3. Use `php octo db/views` to update the views
